/** Layout flags per tema nature-family.
 * Deep-pass selesai untuk semua tema nature-family (audit scrape per tema).
 */

export type NatureLayoutFlags = {
  showMarquee: boolean
  eventsVariant: 'overlay' | 'split' | 'classic' | 'banner' | 'stack' | 'plain' | 'badge'
  storyVariant: 'text' | 'lux'
  mapsEmbed: boolean
  verseInCouple: boolean
  coupleReveal: 'simple' | 'granular'
  galleryAfterStory: boolean
  galleryBeforeGift: boolean
  timelineVariant: 'list' | 'conference'
  timelineOnStoryBg: boolean
  giftVariant: 'toggle' | 'cards'
  thankVariant: 'text' | 'photo-pill' | 'photo-rect' | 'photo-arch' | 'photo-arch-top'
  galleryAnim: 'zoom' | 'alternate'
  showProtocolNote: boolean
  showLiveStreaming: boolean
}

export const NATURE_LAYOUTS = {
  'classic-devotion': {
    showMarquee: true,
    eventsVariant: 'classic',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: false,
    galleryBeforeGift: true,
    timelineVariant: 'conference',
    timelineOnStoryBg: true,
    giftVariant: 'cards',
    thankVariant: 'photo-rect',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'red-essence': {
    showMarquee: true,
    eventsVariant: 'banner',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: false,
    galleryBeforeGift: true,
    timelineVariant: 'conference',
    timelineOnStoryBg: true,
    giftVariant: 'cards',
    thankVariant: 'photo-arch',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'snow-blue': {
    showMarquee: true,
    eventsVariant: 'stack',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-pill',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'snow-pink': {
    showMarquee: true,
    eventsVariant: 'stack',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-pill',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'burgundy-pure': {
    showMarquee: false,
    eventsVariant: 'split',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-pill',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'bear-brown': {
    showMarquee: false,
    eventsVariant: 'plain',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-arch-top',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'infinite-gallop': {
    showMarquee: false,
    eventsVariant: 'plain',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-pill',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'sun-moon': {
    showMarquee: false,
    eventsVariant: 'badge',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-arch-top',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'royal-mega': {
    showMarquee: false,
    eventsVariant: 'plain',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-pill',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'retro-romance': {
    showMarquee: false,
    eventsVariant: 'plain',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-rect',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'padang-red': {
    showMarquee: false,
    eventsVariant: 'plain',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-pill',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'nea-pure': {
    showMarquee: false,
    eventsVariant: 'split',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-arch-top',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'pink-envelope': {
    showMarquee: true,
    eventsVariant: 'split',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-pill',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'java-emerald': {
    showMarquee: true,
    eventsVariant: 'split',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-pill',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'java-atelier': {
    showMarquee: false,
    eventsVariant: 'plain',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-pill',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'maso-rustic': {
    showMarquee: false,
    eventsVariant: 'plain',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-arch-top',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'islamic-eternal': {
    showMarquee: false,
    eventsVariant: 'plain',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-pill',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'islamic-serenity': {
    showMarquee: false,
    eventsVariant: 'plain',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-pill',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'islamic-pure': {
    showMarquee: false,
    eventsVariant: 'badge',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-pill',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
  'chinese-red': {
    showMarquee: false,
    eventsVariant: 'plain',
    storyVariant: 'lux',
    mapsEmbed: true,
    verseInCouple: true,
    coupleReveal: 'granular',
    galleryAfterStory: true,
    galleryBeforeGift: false,
    timelineVariant: 'conference',
    timelineOnStoryBg: false,
    giftVariant: 'cards',
    thankVariant: 'photo-pill',
    galleryAnim: 'alternate',
    showProtocolNote: true,
    showLiveStreaming: true,
  },
} as const satisfies Record<string, NatureLayoutFlags>
