/** Auto-generated from reference/scrape-section-styles — jangan edit manual.
 * Regenerate: node scripts/generate-section-skins.mjs
 */
import type { NatureThemeId } from './natureSkins'

export type SectionSkinStyle = {
  background: string
  onAccent?: 'light' | 'dark'
}

export type NatureSectionSkins = {
  header: SectionSkinStyle
  couple: SectionSkinStyle
  intro: SectionSkinStyle
  events: SectionSkinStyle & { cardRadius: string }
  story: SectionSkinStyle
  gift: SectionSkinStyle
  rsvp: SectionSkinStyle
  gallery: SectionSkinStyle
  footer: SectionSkinStyle
}

export const SECTION_SKINS: Record<NatureThemeId, NatureSectionSkins> = {
  'classic-devotion': {
    header: { background: 'var(--color-secondary)', onAccent: 'light' },
    couple: { background: 'var(--color-primary)' },
    intro: { background: 'var(--color-primary)' },
    events: { background: 'var(--color-secondary)', onAccent: 'light', cardRadius: '25px' },
    story: { background: 'var(--color-primary)' },
    gift: { background: 'var(--color-secondary)', onAccent: 'light' },
    rsvp: { background: 'var(--color-primary)', onAccent: 'dark' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: '#FFFFFF', onAccent: 'dark' },
  },
  'red-essence': {
    header: { background: 'var(--color-secondary)', onAccent: 'light' },
    couple: { background: 'var(--color-primary)' },
    intro: { background: 'var(--color-primary)' },
    events: { background: 'var(--color-secondary)', onAccent: 'light', cardRadius: '30px 0 30px 0' },
    story: { background: 'var(--color-primary)' },
    gift: { background: 'var(--color-secondary)', onAccent: 'light' },
    rsvp: { background: 'var(--color-primary)', onAccent: 'dark' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: '#FFFFFF', onAccent: 'dark' },
  },
  'snow-blue': {
    header: { background: '#FFFFFF', onAccent: 'dark' },
    couple: { background: 'var(--color-secondary)' },
    intro: { background: '#DCEAF3' },
    events: { background: 'var(--color-primary)', onAccent: 'dark', cardRadius: '14px' },
    story: { background: '#DCEAF3' },
    gift: { background: 'linear-gradient(180deg, #FFFFFF 0%, #9bcef6 70%)', onAccent: 'dark' },
    rsvp: { background: 'var(--color-primary)', onAccent: 'dark' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: '#FFFFFF', onAccent: 'dark' },
  },
  'snow-pink': {
    header: { background: 'var(--color-secondary)', onAccent: 'light' },
    couple: { background: 'var(--color-primary)' },
    intro: { background: 'var(--color-primary)' },
    events: { background: 'var(--color-secondary)', onAccent: 'light', cardRadius: '14px' },
    story: { background: 'var(--color-primary)' },
    gift: { background: '#fad9e5', onAccent: 'light' },
    rsvp: { background: 'var(--color-primary)', onAccent: 'dark' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: '#FFFFFF', onAccent: 'dark' },
  },
  'burgundy-pure': {
    header: { background: 'var(--color-other)', onAccent: 'light' },
    couple: { background: 'var(--color-secondary)' },
    intro: { background: 'var(--color-secondary)' },
    events: { background: '#f6f7f0', onAccent: 'dark', cardRadius: '20px' },
    story: { background: 'var(--color-secondary)' },
    gift: { background: '#f6f7f0', onAccent: 'dark' },
    rsvp: { background: 'var(--color-secondary)', onAccent: 'light' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: '#f6f7f0', onAccent: 'dark' },
  },
  'bear-brown': {
    header: { background: 'var(--color-other)', onAccent: 'light' },
    couple: { background: '#F6ECE2' },
    intro: { background: '#F6ECE2' },
    events: { background: '#F6ECE2', onAccent: 'dark', cardRadius: '14px' },
    story: { background: '#F6ECE2' },
    gift: { background: '#F6ECE2', onAccent: 'dark' },
    rsvp: { background: '#F6ECE2', onAccent: 'dark' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: '#F6ECE2', onAccent: 'dark' },
  },
  'infinite-gallop': {
    header: { background: 'var(--color-other)', onAccent: 'light' },
    couple: { background: '#3f0000' },
    intro: { background: '#3f0000' },
    events: { background: '#3f0000', onAccent: 'light', cardRadius: '14px' },
    story: { background: '#3f0000' },
    gift: { background: '#3f0000', onAccent: 'light' },
    rsvp: { background: '#3f0000', onAccent: 'light' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: '#3f0000', onAccent: 'light' },
  },
  'sun-moon': {
    header: { background: '#16323f', onAccent: 'light' },
    couple: { background: '#16323f' },
    intro: { background: '#16323f' },
    events: { background: '#16323f', onAccent: 'light', cardRadius: '14px' },
    story: { background: '#16323f' },
    gift: { background: '#16323f', onAccent: 'light' },
    rsvp: { background: '#16323f', onAccent: 'light' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: '#16323f', onAccent: 'light' },
  },
  'royal-mega': {
    header: { background: '#000000', onAccent: 'light' },
    couple: { background: '#000000' },
    intro: { background: '#000000' },
    events: { background: '#000000', onAccent: 'light', cardRadius: '14px' },
    story: { background: '#000000' },
    gift: { background: '#000000', onAccent: 'light' },
    rsvp: { background: '#000000', onAccent: 'light' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: '#000000', onAccent: 'light' },
  },
  'retro-romance': {
    header: { background: 'var(--color-primary)', onAccent: 'dark' },
    couple: { background: 'var(--color-primary)' },
    intro: { background: 'var(--color-primary)' },
    events: { background: 'var(--color-primary)', onAccent: 'dark', cardRadius: '14px' },
    story: { background: 'var(--color-primary)' },
    gift: { background: 'var(--color-primary)', onAccent: 'dark' },
    rsvp: { background: 'var(--color-primary)', onAccent: 'dark' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: 'var(--color-primary)', onAccent: 'dark' },
  },
  'padang-red': {
    header: { background: '#DC7E89', onAccent: 'light' },
    couple: { background: '#DC7E89' },
    intro: { background: '#DC7E89' },
    events: { background: '#DC7E89', onAccent: 'light', cardRadius: '14px' },
    story: { background: '#DC7E89' },
    gift: { background: '#DC7E89', onAccent: 'light' },
    rsvp: { background: '#DC7E89', onAccent: 'light' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: '#DC7E89', onAccent: 'light' },
  },
  'nea-pure': {
    header: { background: 'var(--color-other)', onAccent: 'light' },
    couple: { background: '#FFFFFF' },
    intro: { background: '#FFFFFF' },
    events: { background: '#FFFFFF', onAccent: 'dark', cardRadius: '20px' },
    story: { background: '#FFFFFF' },
    gift: { background: 'var(--color-secondary)', onAccent: 'light' },
    rsvp: { background: '#FFFFFF', onAccent: 'dark' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: 'var(--color-secondary)', onAccent: 'light' },
  },
  'pink-envelope': {
    header: { background: 'var(--color-secondary)', onAccent: 'light' },
    couple: { background: 'var(--color-primary)' },
    intro: { background: 'var(--color-primary)' },
    events: { background: 'var(--color-secondary)', onAccent: 'light', cardRadius: '20px' },
    story: { background: 'var(--color-primary)' },
    gift: { background: 'var(--color-secondary)', onAccent: 'light' },
    rsvp: { background: 'var(--color-primary)', onAccent: 'dark' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: 'var(--color-secondary)', onAccent: 'light' },
  },
  'java-emerald': {
    header: { background: '#1C3000', onAccent: 'light' },
    couple: { background: 'var(--color-primary)' },
    intro: { background: 'var(--color-primary)' },
    events: { background: 'var(--color-heading)', onAccent: 'dark', cardRadius: '20px' },
    story: { background: 'var(--color-primary)' },
    gift: { background: 'var(--color-other)', onAccent: 'light' },
    rsvp: { background: 'var(--color-heading)', onAccent: 'dark' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: 'var(--color-primary)', onAccent: 'dark' },
  },
  'java-atelier': {
    header: { background: '#F5F0E7', onAccent: 'dark' },
    couple: { background: '#F5F0E7' },
    intro: { background: '#F5F0E7' },
    events: { background: 'var(--color-secondary)', onAccent: 'light', cardRadius: '14px' },
    story: { background: '#F5F0E7' },
    gift: { background: 'var(--color-secondary)', onAccent: 'light' },
    rsvp: { background: 'var(--color-primary)', onAccent: 'dark' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: '#F5F0E7', onAccent: 'dark' },
  },
  'maso-rustic': {
    header: { background: '#FFFFFF', onAccent: 'dark' },
    couple: { background: '#FFFFFF' },
    intro: { background: '#FFFFFF' },
    events: { background: '#FFFFFF', onAccent: 'dark', cardRadius: '14px' },
    story: { background: '#FFFFFF' },
    gift: { background: '#FFFFFF', onAccent: 'dark' },
    rsvp: { background: '#FFFFFF', onAccent: 'dark' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: '#FFFFFF', onAccent: 'dark' },
  },
  'islamic-eternal': {
    header: { background: 'linear-gradient(#094f43, #0A878E, #094f43)', onAccent: 'light' },
    couple: { background: 'linear-gradient(#094f43, #0A878E, #094f43)' },
    intro: { background: 'linear-gradient(#094f43, #0A878E, #094f43)' },
    events: { background: 'linear-gradient(#094f43, #0A878E, #094f43)', onAccent: 'light', cardRadius: '14px' },
    story: { background: 'linear-gradient(#094f43, #0A878E, #094f43)' },
    gift: { background: 'linear-gradient(#094f43, #0A878E, #094f43)', onAccent: 'light' },
    rsvp: { background: 'linear-gradient(#094f43, #0A878E, #094f43)', onAccent: 'light' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: 'linear-gradient(#094f43, #0A878E, #094f43)', onAccent: 'light' },
  },
  'islamic-serenity': {
    header: { background: '#0A878E', onAccent: 'light' },
    couple: { background: '#0A878E' },
    intro: { background: '#0A878E' },
    events: { background: '#0A878E', onAccent: 'light', cardRadius: '14px' },
    story: { background: '#0A878E' },
    gift: { background: '#0A878E', onAccent: 'light' },
    rsvp: { background: '#0A878E', onAccent: 'light' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: '#0A878E', onAccent: 'light' },
  },
  'islamic-pure': {
    header: { background: 'var(--color-other)', onAccent: 'light' },
    couple: { background: 'linear-gradient(#02a09d, #094f43)' },
    intro: { background: 'linear-gradient(#02a09d, #094f43)' },
    events: { background: '#0A878E', onAccent: 'light', cardRadius: '14px' },
    story: { background: 'linear-gradient(#02a09d, #094f43)' },
    gift: { background: 'linear-gradient(#094f43, #02a09d)', onAccent: 'light' },
    rsvp: { background: 'var(--color-heading)', onAccent: 'dark' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: 'linear-gradient(#0A878E, #094f43)', onAccent: 'light' },
  },
  'chinese-red': {
    header: { background: 'var(--color-other)', onAccent: 'light' },
    couple: { background: '#A30000' },
    intro: { background: '#A30000' },
    events: { background: '#A30000', onAccent: 'light', cardRadius: '14px' },
    story: { background: '#A30000' },
    gift: { background: '#A30000', onAccent: 'light' },
    rsvp: { background: '#A30000', onAccent: 'light' },
    gallery: { background: 'var(--color-primary)' },
    footer: { background: '#A30000', onAccent: 'light' },
  },
}
